name: CI/CD Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cmake@v1
        with:
          cmake-version: '3.21'

      - name: Build and run tests
        run: |
          make
          exit_code=0
          for size in 4 6 8 10 12 14 16 18 20; do
            echo "Running tests for matrix size $size"
            echo "$size" | ./matrix_generator
            exit_code=$?
            if [[ $exit_code -ne 0 ]]; then
              echo "Program exited with non-zero code: $exit_code"
              exit 1
            fi
          done
